CREATE TABLE "MEMBER" (
"MEMBER_ID" VARCHAR2(20 BYTE)  PRIMARY KEY, 
"MEMBER_PWD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"MEMBER_NAME" VARCHAR2(50 char) NOT NULL ENABLE, 
"MEMBER_GENDER" VARCHAR2(2 char) NOT NULL ENABLE, 
"MEMBER_EMAIL" VARCHAR2(250 char) UNIQUE, 
"MEMBER_PHONE" CHAR(13 BYTE) UNIQUE, 
"MEMBER_ADDRN" CHAR(5 BYTE) NOT NULL ENABLE, 
"MEMBER_ADDR1" VARCHAR2(100 char) NOT NULL ENABLE, 
"MEMBER_ADDR2" VARCHAR2(100 char) , 
"MEMBER_BIRTHDAY" VARCHAR2(6 BYTE) 
);
	
   COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '아이디';
   COMMENT ON COLUMN "MEMBER"."MEMBER_PWD" IS '비밀번호';
   COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '성명';
   COMMENT ON COLUMN "MEMBER"."MEMBER_GENDER" IS '성별';
   COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '이메일';
   COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS '휴대전화';
   COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRN" IS '우편번호';
   COMMENT ON COLUMN "MEMBER"."MEMBER_ADDR1" IS '주소';
   COMMENT ON COLUMN "MEMBER"."MEMBER_ADDR2" IS '상세주소';
   COMMENT ON COLUMN "MEMBER"."MEMBER_BIRTHDAY" IS '생년월일';
   COMMENT ON TABLE "MEMBER"  IS '회원정보';

